#!/bin/bash
# Usage: setup_mysql <database_name>
# expected ENV: MYSQL_HOST, MYSQL_USER, MYSQL_PASSWORD
# Description:
# Setup the database if it doesn't exist.

if echo "use $1; show tables" | mysql --host=${MYSQL_HOST:-mysql} --user=${MYSQL_USER:-root} --password=${MYSQL_PASSWORD:-root} | grep schema_migrations 2>&1 > /dev/null
then
  echo "🐋 Database exists, doing nothing."
else
  echo "🐋 Setup Database"
  bundle exec rake db:setup
fi
