apiVersion: v1
kind: BuildConfig
metadata:
  name: ruby-trusty
  namespace: ninech
spec:
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: 'ubuntu:trusty'
  output:
    to:
      kind: ImageStreamTag
      name: ruby:trusty
      namespace: ninech
  postCommit:
    script: '/usr/bin/ruby --version'
  resources: {}
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/ninech/baseimage-ruby'
      ref: master
    sourceSecret:
      name: github-token
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        namespace: ninech
        name: 'ubuntu:trusty'
      forcePull: true
  postCommit:
    script: '/usr/bin/ruby2.3 --version'
