apiVersion: v1
kind: BuildConfig
metadata:
  name: ruby
  namespace: ninech
spec:
  triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: <DEFINE A SECRET>
    - type: ImageChange
      imageChange:
  output:
    to:
      kind: ImageStreamTag
      name: ruby:latest
      namespace: ninech
  postCommit:
    script: '/usr/bin/ruby2.3 --version'
  resources: {}
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/ninech/baseimage-ruby'
      ref: master
    sourceSecret:
      name: github-token
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: DockerImage
        namespace: ninech
        name: 'ubuntu:xenial'
      forcePull: true
